theme = "bento"
languageCode = "en-us"
baseurl = "https://frz9.github.io/"
title = "Firaaz Pervez"


author = "Firaaz Pervez"
copyright = "MIT"

[taxonomies]
category = "categories"
tag = "tags"

# Better code higlighting
# via https://discourse.gohugo.io/t/pygmentscodefences-how-to-choose-themes/3842/3
pygmentsCodefences = true
pygmentsStyle = "vs"

# Integrations
googleAnalytics = "UA-XXXXXX-YY"
disqusShortname = "bento-hugo-theme"

# Hightlight theme
[markup.highlight]
  style = "github"
#
# Allow HTML rendering inside markdown
[markup.goldmark.renderer]
  unsafe = true

[params]
  # Show intro in the home page (with headline and description)
  intro = true
  headline = "Hello!"
  description = "I'm a trainee cloud engineer, having spent the last 3 months learning the fundamentals of Linux, Python, Networking, and AWS."

  # Copyright note in the footer
  copyright = "Copyright © 2020 Firaaz Pervez"

  # Image in the homepage. You can setup a different image for social media
  cover = "images/london.jpg"
  ogImage = "images/og_image.jpg"

  # Social media usernames
  github = "Frz9"
  #linkedin = "https://linkedin.com/in/XXXX"
  email = "firaaz.pervez.fp@gmail.com"

  # Avatar (shown in the homepage)
  avatar = "images/avatar.jpg"
  # Bio is shown in the end of posts
  authorBio = "."


# Items in the top menu
[menu]
  [[menu.main]]
      name = "Home"
      url = "/"
      weight = "1"

  [[menu.main]]
      name = "CV"
      url = "/CV/"
      weight = "2"

#  [[menu.main]]
#      name = "Projects"
#      url = "/projects"
#      weight = 0

